// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIhB3_I0-3lRJs-R58_Xk_-6pgNlwuKoc',
    appId: '1:82323424969:web:79c6487689015e0a3a6f18',
    messagingSenderId: '82323424969',
    projectId: 'blogiumapp-cd5d9',
    authDomain: 'blogiumapp-cd5d9.firebaseapp.com',
    storageBucket: 'blogiumapp-cd5d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0FliVYq5jL6wXLbEADxQtZ7MVA8STEtk',
    appId: '1:82323424969:android:56f366fa0ea609ed3a6f18',
    messagingSenderId: '82323424969',
    projectId: 'blogiumapp-cd5d9',
    storageBucket: 'blogiumapp-cd5d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQtsMk9HdYRzWr5k-G3P_XuL2rnjj-3G8',
    appId: '1:82323424969:ios:d15f96279d3b4c133a6f18',
    messagingSenderId: '82323424969',
    projectId: 'blogiumapp-cd5d9',
    storageBucket: 'blogiumapp-cd5d9.firebasestorage.app',
    iosBundleId: 'com.blogium.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQtsMk9HdYRzWr5k-G3P_XuL2rnjj-3G8',
    appId: '1:82323424969:ios:d15f96279d3b4c133a6f18',
    messagingSenderId: '82323424969',
    projectId: 'blogiumapp-cd5d9',
    storageBucket: 'blogiumapp-cd5d9.firebasestorage.app',
    iosBundleId: 'com.blogium.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIhB3_I0-3lRJs-R58_Xk_-6pgNlwuKoc',
    appId: '1:82323424969:web:8118548d5ba7e9a03a6f18',
    messagingSenderId: '82323424969',
    projectId: 'blogiumapp-cd5d9',
    authDomain: 'blogiumapp-cd5d9.firebaseapp.com',
    storageBucket: 'blogiumapp-cd5d9.firebasestorage.app',
  );

}